services:
  moltbot-gateway:
    build:
      context: .
      dockerfile: Dockerfile.custom
    image: my-openclaw:custom
  moltbot-cli:
    build:
      context: .
      dockerfile: Dockerfile.custom
    image: my-openclaw:custom
